### ISSUE TITLE
Typescript declarations

### ISSUE THREAD

**Issue by Alphability** [datocms/vue-datocms#31]
I'm currently trying to use the Structured Texts with Nuxt and Typescript... it is hell.

There are no type declarations exported (unlike _react-datocms_).
I didn't found a way (yet) to use the declarations contained in _datocms-structured-text-utils_ and couple them with _vue-datocms_.

What do you plan to do?
Add declarations to future versions of the package?
Is there a way to use _datocms-structured-text-utils_ and _vue-datocms_ together?

**Comment by stefanoverna** [comment]
Hey @Alphability I'd really like to add TS support to this package, but I've small knowledge of Vue.js and I'm not sure how to proceed. I've tried to find a Vue component package with TS declarations but I haven't had any luck. Do you have any example of a well-structured TS package with tests that we can take as an example? 😄

**Comment by Alphability** [comment]
# Vue + Typescript
I mainly use Nuxt, so the examples of well-structured Vue packages I have mainly come from the Nuxt ecosystem.

## [Nuxt](https://github.com/nuxt/nuxt.js)
The Nuxt repo is useful to see how they define and export their type declarations.

## [Nuxt modules](https://modules.nuxtjs.org)
I know that a lot of the last Nuxt modules are written using Typescript. You should definitely check those packages.
Lately, I used the nuxt/image repo to better set my tsconfig for a private project. 

You should ask Sébastien Chopin (@Atinux) and Pooya Parsa (@pi0) about this issue.
They are great and always help people with this kind of question 👌

**Comment by Alphability** [comment]
# Vue + Typescript
Hey @stefanoverna 👋
I mainly use Nuxt, so the examples of well-structured Vue packages I have mainly come from the Nuxt ecosystem.

## [Nuxt](https://github.com/nuxt/nuxt.js)
The Nuxt repo is useful to see how they define and export their type declarations.

## [Nuxt modules](https://modules.nuxtjs.org)
I know that a lot of the last Nuxt modules are written using Typescript. You should definitely check those packages.
Lately, I used the nuxt/image repo to better set my tsconfig for a private project. 

You should ask Sébastien Chopin (@Atinux) and Pooya Parsa (@pi0) about this issue.
They are great and always help people with this kind of question 👌

**Comment by stefanoverna** [comment]
What we need:

* support both Vue 2 and Vue 3
* expose TS types (I guess only for Vue 3? seems TS on Vue 2 is not a thing)
* keep our tests working

We have just two Vue (rather easy) components. I've tried looking for some simple examples over on Github and https://github.com/vuesomedev/awesome-vue-3 that could satisfy our needs.. no luck so far.

Again, not an expert, but it seems to me that:

* Functional Components signature is completely changed from 2 to 3 (in 3 it's just a pure function). So how can we support both v2 and v3? Probably exporting two different objects?
* To expose TS types, in v3 you need to import Vue's [`defineComponent`](https://v3.vuejs.org/api/global-api.html#definecomponent), which is not defined in v2. So it seems that you cannot have a package that supports both v2 and v3?

I'm confused. And TypeScript usage still seems very rare in Vue-land (maybe one package over 20-30 has types). Again, I'd love to add support to TypeScript, PRs are welcome, but I need some external help to figure out these topics.

**Comment by AdrianRC** [comment]
Hi @stefanoverna, I came across this issue while looking for a way to use the Image component in Vue 3, which seems to be broken due to [this render function API change.](https://v3.vuejs.org/guide/migration/render-function-api.html#_3-x-syntax)

I think what you are looking for is probably [Vue-Demi](https://github.com/vueuse/vue-demi), which is a tool for building libraries that support both Vue 2 and Vue 3. With it, you write your components using the [Composition API syntax](https://v3.vuejs.org/guide/composition-api-introduction.html), which is Vue's equivalent of React Hooks and has much improved TS support.

This is an introductory blog post on the topic: https://dev.to/alvarosaburido/how-to-create-a-universal-library-for-vue-2-3-4lf8
(although I think you can probably get much better DX using [Vite](https://github.com/vitejs/vite))

And here's some example libraries that make use of vue-demi:
- [Villus](https://github.com/logaretm/villus/blob/ef4be0afb8cba12a57c5cc128b999f570898fa69/packages/villus/src/Provider.ts) (Vue's URQL equivalent)
- [Vue Motion](https://github.com/vueuse/motion)
- [Vue Use Stripe](https://github.com/frandiox/vue-use-stripe/blob/4c9212b3146a091d5b75b447e895d7e123fea972/example.ts)

Hope this helps!

**Comment by AdrianRC** [comment]
@stefanoverna I needed the image component for my own uses so I gave rewriting it for Vue 3 a try: https://github.com/AdrianRC/datocms-image/blob/main/src/components/DatoImage.ts

It's a regular Vue 3 + Vite project but the build command outputs only the transpiled ESM + UMD versions of that component. 

I haven't tested it with Vue 2 yet,  but I think it might need some some conditionals in the template to account for the render function API changes, like done here: https://github.com/frandiox/vue-use-stripe/blob/4c9212b3146a091d5b75b447e895d7e123fea972/example.ts

I don't have any real experience building libraries but hopefully this can be useful to you.

**Comment by stefanoverna** [comment]
This is great @AdrianRC, thanks so much! I'll take a look at this ASAP!

**Comment by stefanoverna** [comment]
@AdrianRC, @Alphability I've released `1.0.0-beta.8` which should be Vue 3 compatible (and should also export type definitions). Care to see if it works as expected?

I've followed your template @AdrianRC, thanks so much! https://github.com/datocms/vue-datocms/tree/vue3
