### ISSUE TITLE
Documentation lacks examples

### ISSUE THREAD

**Issue by provok-it** [datocms/vue-datocms#32]
The Structured Text's documentation lacks examples.

For example, using the _customRules_ prop is hard without explanations.

For now, we have to refer to the test file in the source code to try to understand how to use it correctly.

**Comment by stefanoverna** [comment]
You're right @Alphability. Right now the best way is to deduct usage from tests, we'll add a proper section in the README very soon (probably tomorrow!). In the meantime, is there something in particular you are having issues with? What are you trying to achieve?

**Comment by Alphability** [comment]
# A better doc 🙏 

## Context
@stefanoverna I'm currently trying to add syntax highlights to code blocks coming from DatoCMS Structured Texts.
I will probably use [highlight.js](https://github.com/highlightjs/highlight.js).

## The problem
Anyway, I need to use the _customRules prop_ with TypeScript (// @ts-ignore in use to import the package since there are no d.ts exported by it).
In the documentation, there is no example with the _customRules prop_.
It is too hard to understand the package's logic without comments and variables named _"h"_ for example.

## Ideas
It would be great to have an example of each prop in action.
A description of the method's arguments we are getting.

**Comment by matjack1** [comment]
Documentation meanwhile has been improved a lot: https://github.com/datocms/vue-datocms/tree/master/src/components/StructuredText
